name: wordle_ru
description: Русская версия игры Wordle
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.2
  http: ^1.1.0

  # Firebase для синхронизации
  firebase_core: ^4.2.0
  firebase_auth: ^6.1.1
  firebase_auth_web: ^6.0.4
  firebase_database: ^12.0.3

  # Генерация уникальных ID
  uuid: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.0

flutter:
  uses-material-design: true

