// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBytxs5pn_jQnqpTeUusQKus5YhtPWdC-c',
    appId: '1:228393585619:web:1c6e9f4fa7adbb1247bd26',
    messagingSenderId: '228393585619',
    projectId: 'wordle-ru-f1f08',
    authDomain: 'wordle-ru-f1f08.firebaseapp.com',
    databaseURL: 'https://wordle-ru-f1f08-default-rtdb.firebaseio.com',
    storageBucket: 'wordle-ru-f1f08.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOPELu1wvczSivugKyixQ70n5YRTjfSBo',
    appId: '1:228393585619:android:d870e8edec7f091947bd26',
    messagingSenderId: '228393585619',
    projectId: 'wordle-ru-f1f08',
    databaseURL: 'https://wordle-ru-f1f08-default-rtdb.firebaseio.com',
    storageBucket: 'wordle-ru-f1f08.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxjicfYcUSo2xZrviaJY6ws-Yozmmsq98',
    appId: '1:228393585619:ios:ba41e56b37edd9cd47bd26',
    messagingSenderId: '228393585619',
    projectId: 'wordle-ru-f1f08',
    databaseURL: 'https://wordle-ru-f1f08-default-rtdb.firebaseio.com',
    storageBucket: 'wordle-ru-f1f08.firebasestorage.app',
    iosBundleId: 'com.example.wordleRu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxjicfYcUSo2xZrviaJY6ws-Yozmmsq98',
    appId: '1:228393585619:ios:ba41e56b37edd9cd47bd26',
    messagingSenderId: '228393585619',
    projectId: 'wordle-ru-f1f08',
    databaseURL: 'https://wordle-ru-f1f08-default-rtdb.firebaseio.com',
    storageBucket: 'wordle-ru-f1f08.firebasestorage.app',
    iosBundleId: 'com.example.wordleRu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBytxs5pn_jQnqpTeUusQKus5YhtPWdC-c',
    appId: '1:228393585619:web:09daa4fff77b7cf347bd26',
    messagingSenderId: '228393585619',
    projectId: 'wordle-ru-f1f08',
    authDomain: 'wordle-ru-f1f08.firebaseapp.com',
    databaseURL: 'https://wordle-ru-f1f08-default-rtdb.firebaseio.com',
    storageBucket: 'wordle-ru-f1f08.firebasestorage.app',
  );
}
